name: Azure DevOps Migration

on:
  workflow_dispatch:  # Manual trigger

permissions:
  id-token: write
  contents: read

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ADO Migration
        run: |
          python ado_migration.py \
            --source-org "MicrosoftIT" \
            --source-project "Supply Chain Staging" \
            --target-org "msazure" \
            --target-project "One" \
            --source-pat "${{ secrets.SOURCE_PAT }}" \
            --target-pat "${{ secrets.TARGET_PAT }}"
